# Generated by Django 4.0.1 on 2022-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
