# Generated by Django 4.0.1 on 2022-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_emails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
